// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(robot) {
    return robot.respond(/bitcoin/i, function(msg) {
      return msg.http('http://api.bitcoincharts.com/v1/weighted_prices.json').get()(function(err, res, body) {
        var json;

        json = JSON.parse(body);
        return msg.send("BTC: USD$" + json.USD['24h']);
      });
    });
  };

}).call(this);
