// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(robot) {
    return robot.respond(/save this (\w+) (\w+)/i, function(msg) {
      var key, val;

      key = msg.match[1];
      val = msg.match[2];
      return msg.send("Key: " + key + " | Value: " + val);
    });
  };

}).call(this);
